import { loginUser, googleLogin, refreshToken, logout,twoFactorAuth} from "../controllers/user.controllers.js";
import { authenticateToken } from "../middleware/auth.middleware.js";
import express from "express";
const router = express.Router();
router.post("/login", loginUser);
router.post("/google-login", googleLogin);
router.post("/refresh-token", refreshToken);
router.post("/logout", logout);
router.post("/2fa", authenticateToken, twoFactorAuth);
export { router };